// <auto-generated />
using System;
using Henhouse.Logic.Manipulations.Implementations.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Henhouse.Logic.Migrations
{
    [DbContext(typeof(HenhouseDBContext))]
    partial class HenhouseDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Henhouse.Logic.Manipulations.Implementations.EFCore.Models.ChickenModel", b =>
                {
                    b.Property<int>("ChickenModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ChickenModelId");

                    b.ToTable("Chickens");
                });

            modelBuilder.Entity("Henhouse.Logic.Manipulations.Implementations.EFCore.Models.EggModel", b =>
                {
                    b.Property<int>("EggModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ChickenName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsWhite")
                        .HasColumnType("bit");

                    b.Property<int>("WeightInGrams")
                        .HasColumnType("int");

                    b.HasKey("EggModelId");

                    b.ToTable("Eggs");
                });
#pragma warning restore 612, 618
        }
    }
}
